language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sqlite3

install:
  - composer require apache/log4php:2.3.0

script: phpunit tests
