language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sqlite3

install:
  - composer require apache/log4php:2.3.0

script: phpunit tests
